# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0002_auto_20160603_0141'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=200, null=True)),
                ('payment', models.TextField(blank=True, null=True)),
                ('joined_previous_event', models.NullBooleanField()),
                ('previous_event', models.CharField(blank=True, max_length=200, null=True)),
                ('know_about_us', models.CharField(choices=[('FB', 'Facebook'), ('FR', 'Friend'), ('YS', 'Your School'), ('OW', 'Our Website'), ('PE', 'Previous Event')], max_length=2)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.Conference')),
            ],
            options={
                'verbose_name': 'Conference Application',
                'verbose_name_plural': 'Conference Applications',
            },
        ),
        migrations.CreateModel(
            name='TourApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=200, null=True)),
                ('joined_previous_event', models.NullBooleanField()),
                ('previous_event', models.CharField(blank=True, max_length=200, null=True)),
                ('know_about_us', models.CharField(choices=[('FB', 'Facebook'), ('FR', 'Friend'), ('YS', 'Your School'), ('OW', 'Our Website'), ('PE', 'Previous Event')], max_length=2)),
                ('majors', models.ManyToManyField(blank=True, related_name='tour_applications', to='contents.Major')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.Tour')),
            ],
            options={
                'verbose_name': 'Tour Application',
                'verbose_name_plural': 'Tour Applications',
            },
        ),
    ]
