# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('school_name', models.CharField(max_length=200)),
                ('grade_level', models.CharField(max_length=200)),
                ('wave', models.CharField(max_length=200)),
                ('payment', models.TextField(blank=True, null=True)),
                ('joined_previous_event', models.BooleanField(default=False)),
                ('previous_event', models.CharField(blank=True, max_length=200, null=True)),
                ('know_about_us', models.CharField(choices=[('FB', 'Facebook'), ('FR', 'Friend'), ('YS', 'Your School'), ('OW', 'Our Website'), ('PE', 'Previous Event')], max_length=2)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.Conference')),
            ],
            options={
                'verbose_name': 'Conference Application',
                'verbose_name_plural': 'Conference Applications',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Forms',
            },
        ),
        migrations.CreateModel(
            name='OpportunityApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.Opportunity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_applications', to='authentication.Profile')),
            ],
            options={
                'verbose_name': 'Opportunity Application',
                'verbose_name_plural': 'Opportunity Applications',
            },
        ),
        migrations.CreateModel(
            name='TourApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('school_name', models.CharField(max_length=200)),
                ('grade_level', models.CharField(max_length=200)),
                ('wave', models.CharField(max_length=200)),
                ('joined_previous_event', models.BooleanField(default=False)),
                ('previous_event', models.CharField(blank=True, max_length=200, null=True)),
                ('know_about_us', models.CharField(choices=[('FB', 'Facebook'), ('FR', 'Friend'), ('YS', 'Your School'), ('OW', 'Our Website'), ('PE', 'Previous Event')], max_length=2)),
                ('majors', models.ManyToManyField(blank=True, related_name='tour_applications', to='services.Major')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.Tour')),
            ],
            options={
                'verbose_name': 'Tour Application',
                'verbose_name_plural': 'Tour Applications',
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('university', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('year_of_study_graduation', models.CharField(max_length=200)),
                ('why_join', models.TextField()),
                ('experience', models.TextField(blank=True, null=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.Vacancy')),
            ],
            options={
                'verbose_name': 'Vacancy Application',
                'verbose_name_plural': 'Vacancy Applications',
            },
        ),
    ]
