# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunityapplication',
            old_name='profile',
            new_name='user',
        ),
    ]
