# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourapplication',
            name='wave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tourapplication',
            name='joined_previous_event',
            field=models.BooleanField(default=False),
        ),
    ]
