# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-28 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20160727_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
