# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_delete_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsparkApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('parentName', models.CharField(blank=True, max_length=200, null=True)),
                ('parentNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('studentEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('anotherEdu', models.CharField(blank=True, max_length=200, null=True)),
                ('wave', models.CharField(blank=True, max_length=20, null=True)),
                ('statement1', models.IntegerField(blank=True, null=True)),
                ('statement2', models.IntegerField(blank=True, null=True)),
                ('statement3', models.IntegerField(blank=True, null=True)),
                ('statement4', models.IntegerField(blank=True, null=True)),
                ('expectations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'iSpark Application',
                'verbose_name_plural': 'iSpark Applications',
            },
        ),
    ]
