# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-25 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20160725_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyapplication',
            name='confirm_cv',
        ),
    ]
