# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-28 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AD', 'Address'), ('EM', 'Email'), ('PH', 'Phone')], max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='partners')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='SliderSecondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='partners')),
            ],
            options={
                'verbose_name': 'Slider Secondary',
                'verbose_name_plural': 'Sliders Secondary',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='partners')),
                ('text', models.TextField()),
                ('video_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
