# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20160728_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidersecondary',
            name='background',
            field=models.ImageField(upload_to='partners'),
        ),
    ]
