# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20160823_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider Main',
                'verbose_name_plural': 'Sliders Main',
            },
        ),
    ]
