# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_slidermain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('AD', 'Address'), ('EM', 'Email'), ('PH', 'Phone'), ('FB', 'Facebook'), ('TW', 'SnapChat'), ('IN', 'Instagram'), ('YT', 'Youtube'), ('LT', 'Latitude'), ('LG', 'Longitude'), ('PP', 'Phone Students and Parents'), ('PS', 'Phone Schools'), ('PU', 'Phone Universities'), ('PC', 'Phone Companies'), ('SC', 'Students Start Count'), ('JC', 'Jobs Start Count')], max_length=2),
        ),
    ]
