# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_auto_20160910_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 5, 15, 30, 56, 325360, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
