# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 03:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_auto_20160910_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='join_now',
            field=models.CharField(choices=[('J', 'Join iSpark'), ('C', 'Conferences'), ('M', 'Major Exploration')], default='J', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidermain',
            name='url',
            field=models.CharField(default='http://www.isparkegypt.com/', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 11, 3, 21, 36, 234153, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
