# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_auto_20160724_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('AD', 'Address'), ('EM', 'Email'), ('PH', 'Phone'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('YT', 'Youtube'), ('LT', 'Latitude'), ('LG', 'Longitude'), ('PP', 'Phone Students and Parents'), ('PS', 'Phone Schools'), ('PU', 'Phone Universities'), ('PC', 'Phone Companies')], max_length=2),
        ),
    ]
