# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-25 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_auto_20160724_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='team'),
        ),
    ]
