# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_teammember_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
    ]
