# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='fb_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='fb_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
