# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='date',
            new_name='start_date',
        ),
    ]
