# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160728_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
    ]
