# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160605_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
    ]
