# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_tour_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='type',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.CharField(default='J', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='role',
            field=models.CharField(choices=[('I', 'Internship'), ('J', 'Job')], max_length=1),
        ),
    ]
