# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20160910_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
