# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20160910_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='short_description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='short_description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
