# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20160910_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
    ]
