# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20160720_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
