# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_conference_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='contact_email',
        ),
    ]
