# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_conference_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='contact_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
