# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_tour_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='contact_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
