# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-25 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_conference_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='internship_type',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='employer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='opportunities'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='posted_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 7, 25, 22, 6, 29, 520029, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
