# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20160726_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
