# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_category_photo'),
        ('services', '0012_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='contents.Skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='jobs'),
        ),
        migrations.AddField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='jobs'),
        ),
    ]
