# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
